
# This file is automatically generated, you probably don't want to edit this

#' @importFrom jmvcore Options
#' @importFrom R6 R6Class
ClassicMDSOptions <- R6::R6Class(
    "ClassicMDSOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            vars = NULL,
            k = 2,
            label = NULL,
            color = NULL,
            size = NULL,
            dist = "euclidean",
            stand = FALSE, ...) {

            super$initialize(
                package='MTUcluster',
                name='ClassicMDS',
                requiresData=TRUE,
                ...)
        
            private$..vars <- jmvcore::OptionVariables$new(
                "vars",
                vars,
                permitted=list(
                    "continuous"))
            private$..k <- jmvcore::OptionInteger$new(
                "k",
                k,
                default=2,
                min=1)
            private$..label <- jmvcore::OptionVariable$new(
                "label",
                label)
            private$..color <- jmvcore::OptionVariable$new(
                "color",
                color)
            private$..size <- jmvcore::OptionVariable$new(
                "size",
                size)
            private$..dist <- jmvcore::OptionList$new(
                "dist",
                dist,
                options=list(
                    "euclidean",
                    "manhattan"),
                default="euclidean")
            private$..stand <- jmvcore::OptionBool$new(
                "stand",
                stand,
                default=FALSE)
        
            self$.addOption(private$..vars)
            self$.addOption(private$..k)
            self$.addOption(private$..label)
            self$.addOption(private$..color)
            self$.addOption(private$..size)
            self$.addOption(private$..dist)
            self$.addOption(private$..stand)
        }),
    active = list(
        vars = function() private$..vars$value,
        k = function() private$..k$value,
        label = function() private$..label$value,
        color = function() private$..color$value,
        size = function() private$..size$value,
        dist = function() private$..dist$value,
        stand = function() private$..stand$value),
    private = list(
        ..vars = NA,
        ..k = NA,
        ..label = NA,
        ..color = NA,
        ..size = NA,
        ..dist = NA,
        ..stand = NA)
)

#' @import jmvcore
#' @importFrom R6 R6Class
ClassicMDSResults <- R6::R6Class(
    inherit = jmvcore::Group,
    active = list(
        text = function() private$..text,
        plot = function() private$..plot),
    private = list(
        ..text = NA,
        ..plot = NA),
    public=list(
        initialize=function(options) {
            super$initialize(options=options, name="", title="MDS Classic Analysis")
            private$..text <- jmvcore::Preformatted$new(
                options=options,
                name="text",
                title="Results")
            private$..plot <- jmvcore::Image$new(
                options=options,
                name="plot",
                title="MDS Solution",
                width=400,
                height=500,
                renderFun=".plot")
            self$add(private$..text)
            self$add(private$..plot)}))

#' @importFrom jmvcore Analysis
#' @importFrom R6 R6Class
ClassicMDSBase <- R6::R6Class(
    "ClassicMDSBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = 'MTUcluster',
                name = 'ClassicMDS',
                version = c(1,0,0),
                options = options,
                results = ClassicMDSResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE)
        }))

#' MDS Classic Scaling (cmdscale)
#'
#' 
#' @param data .
#' @param vars The variables to use.
#' @param k .
#' @param label .
#' @param color .
#' @param size .
#' @param dist .
#' @param stand .
#' @export
ClassicMDS <- function(
    data,
    vars,
    k = 2,
    label,
    color,
    size,
    dist = "euclidean",
    stand = FALSE) {

    options <- ClassicMDSOptions$new(
        vars = vars,
        k = k,
        label = label,
        color = color,
        size = size,
        dist = dist,
        stand = stand)

    results <- ClassicMDSResults$new(
        options = options)

    analysis <- ClassicMDSClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}
