
# This file is automatically generated, you probably don't want to edit this

#' @importFrom jmvcore Options
#' @importFrom R6 R6Class
DianaOptions <- R6::R6Class(
    "DianaOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            vars = NULL,
            labels = NULL,
            distan = "euclidean",
            stand = FALSE, ...) {

            super$initialize(
                package='MTUcluster',
                name='Diana',
                requiresData=TRUE,
                ...)
        
            private$..vars <- jmvcore::OptionVariables$new(
                "vars",
                vars)
            private$..labels <- jmvcore::OptionVariable$new(
                "labels",
                labels)
            private$..distan <- jmvcore::OptionList$new(
                "distan",
                distan,
                options=list(
                    "euclidean",
                    "maximum",
                    "manhattan",
                    "canberra",
                    "binary",
                    "minkowski"),
                default="euclidean")
            private$..stand <- jmvcore::OptionBool$new(
                "stand",
                stand,
                default=FALSE)
        
            self$.addOption(private$..vars)
            self$.addOption(private$..labels)
            self$.addOption(private$..distan)
            self$.addOption(private$..stand)
        }),
    active = list(
        vars = function() private$..vars$value,
        labels = function() private$..labels$value,
        distan = function() private$..distan$value,
        stand = function() private$..stand$value),
    private = list(
        ..vars = NA,
        ..labels = NA,
        ..distan = NA,
        ..stand = NA)
)

#' @import jmvcore
#' @importFrom R6 R6Class
DianaResults <- R6::R6Class(
    inherit = jmvcore::Group,
    active = list(
        text = function() private$..text,
        plot = function() private$..plot,
        footer = function() private$..footer),
    private = list(
        ..text = NA,
        ..plot = NA,
        ..footer = NA),
    public=list(
        initialize=function(options) {
            super$initialize(options=options, name="", title="Hierarchical Clustering - Divisive")
            private$..text <- jmvcore::Preformatted$new(
                options=options,
                name="text",
                title="Hierarchical Clustering - Divisive")
            private$..plot <- jmvcore::Image$new(
                options=options,
                name="plot",
                title="Dendrogram Plot",
                width=400,
                height=500,
                renderFun=".plot")
            private$..footer <- jmvcore::Preformatted$new(
                options=options,
                name="footer",
                title="About")
            self$add(private$..text)
            self$add(private$..plot)
            self$add(private$..footer)}))

#' @importFrom jmvcore Analysis
#' @importFrom R6 R6Class
DianaBase <- R6::R6Class(
    "DianaBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = 'MTUcluster',
                name = 'Diana',
                version = c(1,0,0),
                options = options,
                results = DianaResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE)
        }))

#' Hierarchical Clustering - Divisive
#'
#' 
#' @param data .
#' @param vars The variables to use.
#' @param labels .
#' @param distan .
#' @param stand .
#' @export
Diana <- function(
    data,
    vars,
    labels,
    distan = "euclidean",
    stand = FALSE) {

    options <- DianaOptions$new(
        vars = vars,
        labels = labels,
        distan = distan,
        stand = stand)

    results <- DianaResults$new(
        options = options)

    analysis <- DianaClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}
