
# This file is automatically generated, you probably don't want to edit this

#' @importFrom jmvcore Options
#' @importFrom R6 R6Class
kmeansOptions <- R6::R6Class(
    "kmeansOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            vars = NULL,
            k = 2,
            algo = "Hartigan-Wong",
            nstart = 10,
            stand = FALSE, ...) {

            super$initialize(
                package='MTUcluster',
                name='kmeans',
                requiresData=TRUE,
                ...)
        
            private$..vars <- jmvcore::OptionVariables$new(
                "vars",
                vars,
                permitted=list(
                    "continuous"))
            private$..k <- jmvcore::OptionInteger$new(
                "k",
                k,
                default=2,
                min=1)
            private$..algo <- jmvcore::OptionList$new(
                "algo",
                algo,
                options=list(
                    "Hartigan-Wong",
                    "Lloyd",
                    "Forgy",
                    "MacQueen"),
                default="Hartigan-Wong")
            private$..nstart <- jmvcore::OptionInteger$new(
                "nstart",
                nstart,
                default=10)
            private$..stand <- jmvcore::OptionBool$new(
                "stand",
                stand,
                default=FALSE)
        
            self$.addOption(private$..vars)
            self$.addOption(private$..k)
            self$.addOption(private$..algo)
            self$.addOption(private$..nstart)
            self$.addOption(private$..stand)
        }),
    active = list(
        vars = function() private$..vars$value,
        k = function() private$..k$value,
        algo = function() private$..algo$value,
        nstart = function() private$..nstart$value,
        stand = function() private$..stand$value),
    private = list(
        ..vars = NA,
        ..k = NA,
        ..algo = NA,
        ..nstart = NA,
        ..stand = NA)
)

#' @import jmvcore
#' @importFrom R6 R6Class
kmeansResults <- R6::R6Class(
    inherit = jmvcore::Group,
    active = list(
        text = function() private$..text,
        clustering = function() private$..clustering,
        centroids = function() private$..centroids,
        plot = function() private$..plot,
        footer = function() private$..footer),
    private = list(
        ..text = NA,
        ..clustering = NA,
        ..centroids = NA,
        ..plot = NA,
        ..footer = NA),
    public=list(
        initialize=function(options) {
            super$initialize(options=options, name="", title="k-Means Clustering")
            private$..text <- jmvcore::Preformatted$new(
                options=options,
                name="text",
                title="Kmeans Clustering")
            private$..clustering <- jmvcore::Table$new(
                options=options,
                name="clustering",
                title="Clustering Table",
                columns=list(
                    list(`name`="cluster", `title`="Cluster ID", `type`="text"),
                    list(`name`="count", `title`="Count", `type`="integer")))
            private$..centroids <- jmvcore::Table$new(
                options=options,
                name="centroids",
                title="Centroids of clusters",
                rows="(k)",
                columns=list(
                    list(`name`=".name[x]", `title`="", `type`="text", `content`="($key)")))
            private$..plot <- jmvcore::Image$new(
                options=options,
                name="plot",
                title="Plot of means across groups",
                width=400,
                height=500,
                renderFun=".plot")
            private$..footer <- jmvcore::Preformatted$new(
                options=options,
                name="footer",
                title="About")
            self$add(private$..text)
            self$add(private$..clustering)
            self$add(private$..centroids)
            self$add(private$..plot)
            self$add(private$..footer)}))

#' @importFrom jmvcore Analysis
#' @importFrom R6 R6Class
kmeansBase <- R6::R6Class(
    "kmeansBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = 'MTUcluster',
                name = 'kmeans',
                version = c(1,0,1),
                options = options,
                results = kmeansResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE)
        }))

#' k-means clustering
#'
#' 
#' @param data .
#' @param vars The variables to use.
#' @param k .
#' @param algo .
#' @param nstart .
#' @param stand .
#' @export
kmeans <- function(
    data,
    vars,
    k = 2,
    algo = "Hartigan-Wong",
    nstart = 10,
    stand = FALSE) {

    options <- kmeansOptions$new(
        vars = vars,
        k = k,
        algo = algo,
        nstart = nstart,
        stand = stand)

    results <- kmeansResults$new(
        options = options)

    analysis <- kmeansClass$new(
        options = options,
        data = data)

    analysis$run()
    analysis$render()

    analysis$results
}
